// app/layout.tsx
import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavbarWrapper from '@/components/NavbarWrapper'
import { ThemeProvider } from "@/components/Theme-provider"
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer'


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const inter = Inter({
  subsets: ['latin'],      // required subset
  variable: '--font-inter', // optional CSS variable
  weight: ['400', '500', '700'], // choose weights you need
});



export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

 

  

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
        
           className={`${inter.className} antialiased`}
          suppressHydrationWarning
        >
          {/* ThemeProvider must wrap whole UI */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
<NavbarWrapper/>   
           <main  >
    {children}
     
    
  </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
